# Generated by Django 4.0.4 on 2022-06-04 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VSNUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=2048)),
                ('preview', models.ImageField(blank=True, upload_to='media/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Video Author+', to='MainAPI.vsnuser')),
                ('dislikes', models.ManyToManyField(related_name='Video Dislikers+', to='MainAPI.vsnuser')),
                ('likes', models.ManyToManyField(related_name='Video Likers+', to='MainAPI.vsnuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2048)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainAPI.vsnuser')),
                ('dislikes', models.ManyToManyField(related_name='Comment Dislikers+', to='MainAPI.vsnuser')),
                ('likes', models.ManyToManyField(related_name='Comment Likers+', to='MainAPI.vsnuser')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainAPI.video')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=2048)),
                ('ignorers', models.ManyToManyField(related_name='Channel ignorers+', to='MainAPI.vsnuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Channel Owner+', to='MainAPI.vsnuser')),
                ('subscribers', models.ManyToManyField(related_name='Channel Subscribers+', to='MainAPI.vsnuser')),
            ],
        ),
    ]
