# Generated by Django 4.0.4 on 2022-07-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPI', '0002_alter_channel_ignorers_alter_channel_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name_plural': 'channels'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'videos'},
        ),
        migrations.AlterModelOptions(
            name='vsnuser',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
