# Generated by Django 4.0.4 on 2022-07-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPI', '0003_alter_channel_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='author',
        ),
        migrations.AddField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_channel', to='MainAPI.vsnuser'),
            preserve_default=False,
        ),
    ]
