# Generated by Django 4.0.4 on 2022-07-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPI', '0005_alter_channel_ignorers_alter_channel_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_channel', to='MainAPI.channel'),
        ),
    ]
